### PR TITLE
add arm builds + update to v0.13.0

### PR DESCRIPTION
**Pull request by pavelzw**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pavelzw** [comment]
@conda-forge-admin, please rerender

**Comment by pavelzw** [comment]
@conda-forge-admin, please rerender

**Comment by pavelzw** [comment]
Depends on [forestci-feedstock#8](https://github.com/conda-forge/forestci-feedstock/pull/8).

**Comment by pavelzw** [comment]
Closes #2

**Review by xhochy — APPROVED** [review]

**Comment by xhochy** [comment]
@pavelzw Can you add yourself as a maintainer?

**Comment by pavelzw** [comment]
Fixes #4

**Pull request merged**
